In [1]:
#required for manipulating data
import pandas as pd
import numpy as np 

#required for building the interactive dashboard
import panel as pn
pn.extension('tabulator')
import hvplot.pandas
import holoviews as hv
hv.extension('bokeh')

In [2]:
# import csv file

df = pd.read_csv('data/transactions_2024.csv')

In [3]:
df

,Date,Name / Description,Expense/Income,Amount (Argentinian Peso)
0,19/01/24,TRANSF. CLIENTE ESPOSITO MARCELO,Income,2000.00
1,19/01/24,TRANSFERENCIA INMEDIATA,Income,980.00
2,22/01/24,IMP PAIS SD,Expense,-130.49
3,22/01/24,APPLE.COM/BILL,Expense,-1731.30
4,22/01/24,RG 4815/20,Expense,-489.36
...,...,...,...,...
120,26/08/24,TRANSFERENCIA,Expense,-30000.00
121,26/08/24,DIA TIENDA 679,Expense,-5436.25
122,27/08/24,VERDULERIA PAOLA,Expense,-7346.00
123,28/08/24,TRANSF. CLIENTE ESPOSITO MARCELO,Income,30000.00
124,28/08/24,COTO SUCURSAL 163,Expense,-8689.48

In [4]:
#clean df

df = df.rename(columns={'Name / Description': 'Description'})   #rename columns
df['Description'] = df['Description'].map(str.lower) #lower case of descriptions
df['Category'] = 'unassigned'                        #add category column

df.head()

,Date,Description,Expense/Income,Amount (Argentinian Peso),Category
0,19/01/24,transf. cliente esposito marcelo,Income,2000.00,unassigned
1,19/01/24,transferencia inmediata,Income,980.00,unassigned
2,22/01/24,imp pais sd,Expense,-130.49,unassigned
3,22/01/24,apple.com/bill,Expense,-1731.30,unassigned
4,22/01/24,rg 4815/20,Expense,-489.36,unassigned

In [5]:
#define all categories

# Bank Transfers
# Tax & Fees
# Digital Services
# Services
# Groceries
# Food & Dining
# Shopping
# Health & Pharmacy
# Interest
# Reimbursement

In [6]:
#Assign transactions to the correct category

# Bank Transfer
df['Category'] = np.where(df['Description'].str.contains(
    'transf|transferencia'), 
    'Bank Transfer', df['Category'])

# Tax & Fees
df['Category'] = np.where(df['Description'].str.contains(
    'imp pais|rg 4815|iva serv digit'), 
    'Tax & Fees', df['Category'])

# Digital Services
df['Category'] = np.where(df['Description'].str.contains(
    'apple.com'), 
    'Digital Services', df['Category'])

# Services
df['Category'] = np.where(df['Description'].str.contains(
    'openpay|merpago|julio cesar estrada|juanlin|lanaturaleza1855'), 
    'Services', df['Category'])

# Groceries
df['Category'] = np.where(df['Description'].str.contains(
    'dia tienda|coto sucursal|pvs*super uruburu jose e|verduleria paola|market avenida'), 
    'Groceries', df['Category'])

# Food & Dining
df['Category'] = np.where(df['Description'].str.contains(
    'fei li|la finca'), 
    'Food & Dining', df['Category'])

# Shopping
df['Category'] = np.where(df['Description'].str.contains(
    'pigmento|new garden'), 
    'Shopping', df['Category'])

# Health & Pharmacy
df['Category'] = np.where(df['Description'].str.contains(
    'farmacity'), 
    'Health & Pharmacy', df['Category'])

# Interest
df['Category'] = np.where(df['Description'].str.contains(
    'intereses ganados'), 
    'Interest', df['Category'])

# Reimbursement
df['Category'] = np.where(df['Description'].str.contains(
    'reintegro modo'), 
    'Reimbursement', df['Category'])

# Convert the "Date" column to a datetime format
df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%y')

# Extract the month and year information
df['Month'] = df['Date'].dt.month
df['Year'] = df['Date'].dt.year

pd.options.display.max_rows = 999
df.head(200)

,Date,Description,Expense/Income,Amount (Argentinian Peso),Category,Month,Year
0,2024-01-19,transf. cliente esposito marcelo,Income,2000.00,Bank Transfer,1,2024
1,2024-01-19,transferencia inmediata,Income,980.00,Bank Transfer,1,2024
2,2024-01-22,imp pais sd,Expense,-130.49,Tax & Fees,1,2024
3,2024-01-22,apple.com/bill,Expense,-1731.30,Digital Services,1,2024
4,2024-01-22,rg 4815/20,Expense,-489.36,Tax & Fees,1,2024
5,2024-01-23,iva serv digit-rg afip 4240,Expense,-363.57,Tax & Fees,1,2024
6,2024-02-28,transf. cliente esposito marcelo,Income,30000.00,Bank Transfer,2,2024
7,2024-02-29,openpay*vida point,Expense,-2900.00,Services,2,2024
8,2024-02-29,dia tienda 268,Expense,-3518.75,Groceries,2,2024
9,2024-02-29,fei li,Expense,-3000.00,Food & Dining,2,2024
10,2024-02-29,merpago*hakuna,Expense,-1802.50,Services,2,2024
11,2024-03-01,intereses ganados,Income,0.07,Interest,3,2024
12,2024-03-01,julio cesar estrada,Expense,-2593.00,Services,3,2024
13,2024-03-04,transf. cliente esposito marcelo,Income,10000.00,Bank Transfer,3,2024
14,2024-03-04,dia tienda 679,Expense,-6310.00,Groceries,3,2024
15,2024-03-04,fei li,Expense,-5800.00,Food & Dining,3,2024
16,2024-03-05,coto sucursal 163,Expense,-3870.38,Groceries,3,2024
17,2024-03-05,pvs*super uruburu jose e,Expense,-7500.00,unassigned,3,2024
18,2024-03-08,transf. cliente esposito marcelo,Income,40000.00,Bank Transfer,3,2024
19,2024-03-11,imp pais sd,Expense,-202.48,Tax & Fees,3,2024
20,2024-03-11,dia tienda 268,Expense,-2690.00,Groceries,3,2024
21,2024-03-11,dia tienda 679,Expense,-4970.00,Groceries,3,2024
22,2024-03-11,fei li,Expense,-3000.00,Food & Dining,3,2024
23,2024-03-11,apple.com/bill,Expense,-2705.95,Digital Services,3,2024
24,2024-03-11,rg 4815/20,Expense,-759.31,Tax & Fees,3,2024
25,2024-03-12,coto sucursal 163,Expense,-8790.73,Groceries,3,2024
26,2024-03-12,merpago*juanlin,Expense,-2850.00,Services,3,2024
27,2024-03-12,iva serv digit-rg afip 4240,Expense,-568.24,Tax & Fees,3,2024
28,2024-03-13,dia tienda 679,Expense,-3557.90,Groceries,3,2024
29,2024-03-13,fei li,Expense,-2950.00,Food & Dining,3,2024
30,2024-03-14,transf. cliente esposito marcelo,Income,30000.00,Bank Transfer,3,2024
31,2024-03-14,verduleria paola,Expense,-1700.00,Groceries,3,2024
32,2024-03-14,fei li,Expense,-3000.00,Food & Dining,3,2024
33,2024-03-14,dia tienda 268,Expense,-3829.50,Groceries,3,2024
34,2024-03-15,dia tienda 679,Expense,-8620.05,Groceries,3,2024
35,2024-03-15,julio cesar estrada,Expense,-1360.00,Services,3,2024
36,2024-03-18,transf. cliente esposito marcelo,Income,10000.00,Bank Transfer,3,2024
37,2024-03-18,transf. cliente esposito marcelo,Income,20000.00,Bank Transfer,3,2024
38,2024-03-18,verduleria paola,Expense,-1215.00,Groceries,3,2024
39,2024-03-18,julio cesar estrada,Expense,-620.00,Services,3,2024
40,2024-03-18,fei li,Expense,-3000.00,Food & Dining,3,2024
41,2024-03-18,pvs*super uruburu jose e,Expense,-6750.00,unassigned,3,2024
42,2024-03-18,farmacity,Expense,-12006.04,Health & Pharmacy,3,2024
43,2024-03-18,merpago*hakuna,Expense,-1767.50,Services,3,2024
44,2024-03-18,dia tienda 679,Expense,-3779.00,Groceries,3,2024
45,2024-03-18,dia tienda 268,Expense,-7603.15,Groceries,3,2024
46,2024-03-18,coto sucursal 163,Expense,-13184.08,Groceries,3,2024
47,2024-04-03,intereses ganados,Income,0.46,Interest,4,2024
48,2024-04-03,transf. cliente esposito marcelo,Income,20000.00,Bank Transfer,4,2024
49,2024-04-03,julio cesar estrada,Expense,-4323.00,Services,4,2024
50,2024-04-03,coto sucursal 163,Expense,-6815.93,Groceries,4,2024
51,2024-04-03,pvs*super uruburu jose e,Expense,-7280.00,unassigned,4,2024
52,2024-04-05,dia tienda 268,Expense,-1974.00,Groceries,4,2024
53,2024-04-10,transf. cliente esposito marcelo,Income,50000.00,Bank Transfer,4,2024
54,2024-04-11,merpago*hakuna,Expense,-1767.50,Services,4,2024
55,2024-04-11,dia tienda 268,Expense,-6505.10,Groceries,4,2024
56,2024-04-11,verduleria paola,Expense,-2095.00,Groceries,4,2024
57,2024-04-11,fei li,Expense,-5200.00,Food & Dining,4,2024
58,2024-04-12,dia tienda 679,Expense,-6789.00,Groceries,4,2024
59,2024-04-15,verduleria paola,Expense,-7311.00,Groceries,4,2024
60,2024-04-15,merpago*juanlin,Expense,-3000.00,Services,4,2024
61,2024-04-15,pigmento,Expense,-2790.00,Shopping,4,2024
62,2024-04-15,fei li,Expense,-5900.00,Food & Dining,4,2024
63,2024-04-16,dia tienda 268,Expense,-4369.00,Groceries,4,2024
64,2024-04-16,fei li,Expense,-4650.00,Food & Dining,4,2024
65,2024-04-22,transf. cliente tejerina maria,Income,3000.00,Bank Transfer,4,2024
66,2024-04-22,transf. cliente tejerina maria,Income,7600.00,Bank Transfer,4,2024
67,2024-04-22,pigmento,Expense,-4218.57,Shopping,4,2024
68,2024-04-23,verduleria paola,Expense,-5885.00,Groceries,4,2024
69,2024-05-02,intereses ganados,Income,0.26,Interest,5,2024
70,2024-05-24,transf. cliente esposito marcelo,Income,100000.00,Bank Transfer,5,2024
71,2024-05-27,merpago*lanaturaleza1855,Expense,-11900.00,Services,5,2024
72,2024-05-27,market avenida sta. fe,Expense,-8836.44,Groceries,5,2024
73,2024-05-27,dia tienda 679,Expense,-8578.60,Groceries,5,2024
74,2024-05-28,new garden,Expense,-7495.00,Shopping,5,2024
75,2024-05-28,merpago*juanlin,Expense,-4700.00,Services,5,2024
76,2024-05-29,coto sucursal 163,Expense,-14979.32,Groceries,5,2024
77,2024-05-30,merpago*lanaturaleza1855,Expense,-5800.00,Services,5,2024
78,2024-05-30,la finca,Expense,-7760.00,Food & Dining,5,2024
79,2024-05-30,dia tienda 268,Expense,-4237.40,Groceries,5,2024
80,2024-05-31,merpago*juanlin,Expense,-7840.00,Services,5,2024
81,2024-06-03,intereses ganados,Income,0.73,Interest,6,2024
82,2024-06-06,merpago*juanlin,Expense,-14000.00,Services,6,2024
83,2024-06-06,new garden,Expense,-4400.00,Shopping,6,2024
84,2024-07-01,intereses ganados,Income,0.15,Interest,7,2024
85,2024-07-01,transf. cliente esposito marcelo,Income,100000.00,Bank Transfer,7,2024
86,2024-07-01,transferencia,Expense,-30000.00,Bank Transfer,7,2024
87,2024-07-03,coto sucursal 163,Expense,-19067.60,Groceries,7,2024
88,2024-07-04,transf. cliente tejerina maria,Income,10000.00,Bank Transfer,7,2024
89,2024-07-05,new garden,Expense,-9400.00,Shopping,7,2024
90,2024-07-08,verduleria paola,Expense,-11287.00,Groceries,7,2024
91,2024-07-10,imp pais sd,Expense,-219.70,Tax & Fees,7,2024
92,2024-07-10,apple.com bill,Expense,-2900.30,Digital Services,7,2024
93,2024-07-10,coto sucursal 163,Expense,-11432.29,Groceries,7,2024
94,2024-07-10,rg 4815/20,Expense,-823.89,Tax & Fees,7,2024
95,2024-07-11,iva serv digit-rg afip 4240,Expense,-609.06,Tax & Fees,7,2024
96,2024-07-12,merpago*juanlin,Expense,-10750.00,Services,7,2024
97,2024-07-12,verduleria paola,Expense,-4338.00,Groceries,7,2024
98,2024-07-12,new garden,Expense,-4400.00,Shopping,7,2024
99,2024-07-15,transf. cliente esposito marcelo,Income,50000.00,Bank Transfer,7,2024
100,2024-07-15,dia tienda 268,Expense,-9481.70,Groceries,7,2024
101,2024-07-15,transferencia,Expense,-20000.00,Bank Transfer,7,2024
102,2024-07-15,transferencia,Expense,-10000.00,Bank Transfer,7,2024
103,2024-07-16,dia tienda 679,Expense,-7595.90,Groceries,7,2024
104,2024-07-19,transferencia,Expense,-8388.09,Bank Transfer,7,2024
105,2024-07-22,transf. cliente esposito marcelo,Income,50000.00,Bank Transfer,7,2024
106,2024-07-22,transferencia,Expense,-30000.00,Bank Transfer,7,2024
107,2024-07-22,dia tienda 679,Expense,-9075.41,Groceries,7,2024
108,2024-07-25,reintegro modo. 100% en tu prim,Income,5000.00,Reimbursement,7,2024
109,2024-07-25,reintegro modo. 20% en cualquie,Income,1000.00,Reimbursement,7,2024
110,2024-07-29,transferencia,Expense,-16924.00,Bank Transfer,7,2024
111,2024-08-01,intereses ganados,Income,0.94,Interest,8,2024
112,2024-08-07,transf. cliente esposito marcelo,Income,20000.00,Bank Transfer,8,2024
113,2024-08-09,verduleria paola,Expense,-3612.00,Groceries,8,2024
114,2024-08-12,imp pais sd,Expense,-224.60,Tax & Fees,8,2024
115,2024-08-12,apple.com/bill,Expense,-2972.06,Digital Services,8,2024
116,2024-08-12,rg 4815/20,Expense,-842.28,Tax & Fees,8,2024
117,2024-08-13,iva serv digit-rg afip 4240,Expense,-624.13,Tax & Fees,8,2024
118,2024-08-26,transf. cliente esposito marcelo,Income,50000.00,Bank Transfer,8,2024
119,2024-08-26,verduleria paola,Expense,-8552.00,Groceries,8,2024
120,2024-08-26,transferencia,Expense,-30000.00,Bank Transfer,8,2024
121,2024-08-26,dia tienda 679,Expense,-5436.25,Groceries,8,2024
122,2024-08-27,verduleria paola,Expense,-7346.00,Groceries,8,2024
123,2024-08-28,transf. cliente esposito marcelo,Income,30000.00,Bank Transfer,8,2024
124,2024-08-28,coto sucursal 163,Expense,-8689.48,Groceries,8,2024

In [7]:
#check unassigned transactions and confirm all transactions are assigned to a category

unassigned = df.loc[df['Category'] == 'unassigned']
unassigned

,Date,Description,Expense/Income,Amount (Argentinian Peso),Category,Month,Year
17,2024-03-05,pvs*super uruburu jose e,Expense,-7500.0,unassigned,3,2024
41,2024-03-18,pvs*super uruburu jose e,Expense,-6750.0,unassigned,3,2024
51,2024-04-03,pvs*super uruburu jose e,Expense,-7280.0,unassigned,4,2024

## Create Top Banner for a summary of last month's income, recurring expenses, non-recurring expenses and savings

In [8]:
# Get the latest month and year
latest_month = df['Month'].max()
latest_year = df['Year'].max()

# Filter the dataframe to include only transactions from the latest month
last_month_expenses = df[(df['Month'] == latest_month) & (df['Year'] == latest_year)]

In [9]:
last_month_expenses = last_month_expenses.groupby('Category')['Amount (Argentinian Peso)'].sum().reset_index()

last_month_expenses['Amount (Argentinian Peso)']=last_month_expenses['Amount (Argentinian Peso)'].astype('str')
last_month_expenses['Amount (Argentinian Peso)']=last_month_expenses['Amount (Argentinian Peso)'].str.replace('-','')
last_month_expenses['Amount (Argentinian Peso)']=last_month_expenses['Amount (Argentinian Peso)'].astype('float')        #get absolute figures

last_month_expenses = last_month_expenses[last_month_expenses["Category"].str.contains("unassigned") == False]    #exclude "unassigned" category
last_month_expenses = last_month_expenses.sort_values(by='Amount (Argentinian Peso)', ascending=False)    #sort values
last_month_expenses['Amount (Argentinian Peso)'] = last_month_expenses['Amount (Argentinian Peso)'].round().astype(int)      #round values

last_month_expenses

           Category  Amount (Argentinian Peso)
0     Bank Transfer                      70000
2         Groceries                      33636
1  Digital Services                       2972
4        Tax & Fees                       1691
3          Interest                          1

In [10]:
last_month_expenses_tot = last_month_expenses['Amount (Argentinian Peso)'].sum()
last_month_expenses_tot

np.int64(108300)

In [11]:
def calculate_difference(event):
    income = float(income_widget.value)
    recurring_expenses = float(recurring_expenses_widget.value)
    monthly_expenses = float(monthly_expenses_widget.value)
    difference = income - recurring_expenses - monthly_expenses
    difference_widget.value = str(difference)

income_widget = pn.widgets.TextInput(name="Income", value="0")
recurring_expenses_widget = pn.widgets.TextInput(name="Recurring Expenses", value="0")
monthly_expenses_widget = pn.widgets.TextInput(name="Non-Recurring Expenses", value=str(last_month_expenses_tot))
difference_widget = pn.widgets.TextInput(name="Last Month's Savings", value="0")

income_widget.param.watch(calculate_difference, "value")
recurring_expenses_widget.param.watch(calculate_difference, "value")
monthly_expenses_widget.param.watch(calculate_difference, "value")

pn.Row(income_widget, recurring_expenses_widget, monthly_expenses_widget, difference_widget).show()

Launching server at http://localhost:64593

## Create last month expenses bar chart

In [12]:
last_month_expenses_chart = last_month_expenses.hvplot.bar(
    x='Category', 
    y='Amount (Argentinian Peso)', 
    height=250, 
    width=850, 
    title="Last Month Expenses",
    ylim=(0, 500))

last_month_expenses_chart

:Bars   [Category]   (Amount (Argentinian Peso))

## Create monthly expenses trend bar chart

In [13]:
df['Date'] = pd.to_datetime(df['Date'])            # convert the 'Date' column to a datetime object
df['Month-Year'] = df['Date'].dt.to_period('M')    # extract the month and year from the 'Date' column and create a new column 'Month-Year'
monthly_expenses_trend_by_cat = df.groupby(['Month-Year', 'Category'])['Amount (Argentinian Peso)'].sum().reset_index()

monthly_expenses_trend_by_cat['Amount (Argentinian Peso)']=monthly_expenses_trend_by_cat['Amount (Argentinian Peso)'].astype('str')
monthly_expenses_trend_by_cat['Amount (Argentinian Peso)']=monthly_expenses_trend_by_cat['Amount (Argentinian Peso)'].str.replace('-','')
monthly_expenses_trend_by_cat['Amount (Argentinian Peso)']=monthly_expenses_trend_by_cat['Amount (Argentinian Peso)'].astype('float')
monthly_expenses_trend_by_cat = monthly_expenses_trend_by_cat[monthly_expenses_trend_by_cat["Category"].str.contains("unassigned") == False]

monthly_expenses_trend_by_cat = monthly_expenses_trend_by_cat.sort_values(by='Amount (Argentinian Peso)', ascending=False)
monthly_expenses_trend_by_cat['Amount (Argentinian Peso)'] = monthly_expenses_trend_by_cat['Amount (Argentinian Peso)'].round().astype(int)
monthly_expenses_trend_by_cat['Month-Year'] = monthly_expenses_trend_by_cat['Month-Year'].astype(str)
monthly_expenses_trend_by_cat = monthly_expenses_trend_by_cat.rename(columns={'Amount (Argentinian Peso)':'Amount (Argentinian Peso)'})

monthly_expenses_trend_by_cat

   Month-Year           Category  Amount (Argentinian Peso)
7     2024-03      Bank Transfer                     110000
23    2024-05      Bank Transfer                     100000
32    2024-07      Bank Transfer                      94688
16    2024-04      Bank Transfer                      80600
34    2024-07          Groceries                      72278
10    2024-03          Groceries                      70120
40    2024-08      Bank Transfer                      70000
18    2024-04          Groceries                      41744
25    2024-05          Groceries                      36632
42    2024-08          Groceries                      33636
27    2024-05           Services                      30240
3     2024-02      Bank Transfer                      30000
9     2024-03      Food & Dining                      17750
17    2024-04      Food & Dining                      15750
30    2024-06           Services                      14000
38    2024-07           Shopping                      13800
11    2024-03  Health & Pharmacy                      12006
37    2024-07           Services                      10750
13    2024-03           Services                       9190
20    2024-04           Services                       9090
24    2024-05      Food & Dining                       7760
28    2024-05           Shopping                       7495
21    2024-04           Shopping                       7009
36    2024-07      Reimbursement                       6000
6     2024-02           Services                       4702
31    2024-06           Shopping                       4400
5     2024-02          Groceries                       3519
4     2024-02      Food & Dining                       3000
0     2024-01      Bank Transfer                       2980
41    2024-08   Digital Services                       2972
33    2024-07   Digital Services                       2900
8     2024-03   Digital Services                       2706
1     2024-01   Digital Services                       1731
44    2024-08         Tax & Fees                       1691
39    2024-07         Tax & Fees                       1653
14    2024-03         Tax & Fees                       1530
2     2024-01         Tax & Fees                        983
43    2024-08           Interest                          1
29    2024-06           Interest                          1
19    2024-04           Interest                          0
26    2024-05           Interest                          0
35    2024-07           Interest                          0
12    2024-03           Interest                          0

In [14]:
#Define Panel widget

select_category1 = pn.widgets.Select(name='Select Category', options=[
    'All',
    'Bank Transfer',
    'Tax & Fees',
    'Digital Services',
    'Services',
    'Groceries',
    'Food & Dining',
    'Shopping',
    'Health & Pharmacy',
    'Interest',
    'Reimbursement',
])

select_category1

BokehModel(combine_events=True, render_bundle={'docs_json': {'abbb6401-c530-4d6e-bd0e-d3d84ad29179': {'version…

In [15]:
# define plot function
def plot_expenses(category):
    if category == 'All':
        plot_df = monthly_expenses_trend_by_cat.groupby('Month-Year').sum()
    else:
        plot_df = monthly_expenses_trend_by_cat[monthly_expenses_trend_by_cat['Category'] == category].groupby('Month-Year').sum()
    plot = plot_df.hvplot.bar(x='Month-Year', y='Amount (Argentinian Peso)')
    return plot

# define callback function
@pn.depends(select_category1.param.value)
def update_plot(category):
    plot = plot_expenses(category)
    return plot

# create layout
monthly_expenses_trend_by_cat_chart = pn.Row(select_category1, update_plot)
monthly_expenses_trend_by_cat_chart[1].width = 600

monthly_expenses_trend_by_cat_chart

BokehModel(combine_events=True, render_bundle={'docs_json': {'4fc62060-1da2-4666-a73a-d1a417cba2a3': {'version…

## Create summary table

In [16]:
df = df[['Date', 'Category', 'Description', 'Amount (Argentinian Peso)']]
df['Amount (Argentinian Peso)']=df['Amount (Argentinian Peso)'].astype('str')
df['Amount (Argentinian Peso)']=df['Amount (Argentinian Peso)'].str.replace('-','')
df['Amount (Argentinian Peso)']=df['Amount (Argentinian Peso)'].astype('float')        #get absolute figures

df = df[df["Category"].str.contains("unassigned") == False]    #exclude "unassigned" category
df['Amount (Argentinian Peso)'] = df['Amount (Argentinian Peso)'].round().astype(int)      #round values
df

,Date,Category,Description,Amount (Argentinian Peso)
0,2024-01-19,Bank Transfer,transf. cliente esposito marcelo,2000
1,2024-01-19,Bank Transfer,transferencia inmediata,980
2,2024-01-22,Tax & Fees,imp pais sd,130
3,2024-01-22,Digital Services,apple.com/bill,1731
4,2024-01-22,Tax & Fees,rg 4815/20,489
5,2024-01-23,Tax & Fees,iva serv digit-rg afip 4240,364
6,2024-02-28,Bank Transfer,transf. cliente esposito marcelo,30000
7,2024-02-29,Services,openpay*vida point,2900
8,2024-02-29,Groceries,dia tienda 268,3519
9,2024-02-29,Food & Dining,fei li,3000
10,2024-02-29,Services,merpago*hakuna,1802
11,2024-03-01,Interest,intereses ganados,0
12,2024-03-01,Services,julio cesar estrada,2593
13,2024-03-04,Bank Transfer,transf. cliente esposito marcelo,10000
14,2024-03-04,Groceries,dia tienda 679,6310
15,2024-03-04,Food & Dining,fei li,5800
16,2024-03-05,Groceries,coto sucursal 163,3870
18,2024-03-08,Bank Transfer,transf. cliente esposito marcelo,40000
19,2024-03-11,Tax & Fees,imp pais sd,202
20,2024-03-11,Groceries,dia tienda 268,2690
21,2024-03-11,Groceries,dia tienda 679,4970
22,2024-03-11,Food & Dining,fei li,3000
23,2024-03-11,Digital Services,apple.com/bill,2706
24,2024-03-11,Tax & Fees,rg 4815/20,759
25,2024-03-12,Groceries,coto sucursal 163,8791
26,2024-03-12,Services,merpago*juanlin,2850
27,2024-03-12,Tax & Fees,iva serv digit-rg afip 4240,568
28,2024-03-13,Groceries,dia tienda 679,3558
29,2024-03-13,Food & Dining,fei li,2950
30,2024-03-14,Bank Transfer,transf. cliente esposito marcelo,30000
31,2024-03-14,Groceries,verduleria paola,1700
32,2024-03-14,Food & Dining,fei li,3000
33,2024-03-14,Groceries,dia tienda 268,3830
34,2024-03-15,Groceries,dia tienda 679,8620
35,2024-03-15,Services,julio cesar estrada,1360
36,2024-03-18,Bank Transfer,transf. cliente esposito marcelo,10000
37,2024-03-18,Bank Transfer,transf. cliente esposito marcelo,20000
38,2024-03-18,Groceries,verduleria paola,1215
39,2024-03-18,Services,julio cesar estrada,620
40,2024-03-18,Food & Dining,fei li,3000
42,2024-03-18,Health & Pharmacy,farmacity,12006
43,2024-03-18,Services,merpago*hakuna,1768
44,2024-03-18,Groceries,dia tienda 679,3779
45,2024-03-18,Groceries,dia tienda 268,7603
46,2024-03-18,Groceries,coto sucursal 163,13184
47,2024-04-03,Interest,intereses ganados,0
48,2024-04-03,Bank Transfer,transf. cliente esposito marcelo,20000
49,2024-04-03,Services,julio cesar estrada,4323
50,2024-04-03,Groceries,coto sucursal 163,6816
52,2024-04-05,Groceries,dia tienda 268,1974
53,2024-04-10,Bank Transfer,transf. cliente esposito marcelo,50000
54,2024-04-11,Services,merpago*hakuna,1768
55,2024-04-11,Groceries,dia tienda 268,6505
56,2024-04-11,Groceries,verduleria paola,2095
57,2024-04-11,Food & Dining,fei li,5200
58,2024-04-12,Groceries,dia tienda 679,6789
59,2024-04-15,Groceries,verduleria paola,7311
60,2024-04-15,Services,merpago*juanlin,3000
61,2024-04-15,Shopping,pigmento,2790
62,2024-04-15,Food & Dining,fei li,5900
63,2024-04-16,Groceries,dia tienda 268,4369
64,2024-04-16,Food & Dining,fei li,4650
65,2024-04-22,Bank Transfer,transf. cliente tejerina maria,3000
66,2024-04-22,Bank Transfer,transf. cliente tejerina maria,7600
67,2024-04-22,Shopping,pigmento,4219
68,2024-04-23,Groceries,verduleria paola,5885
69,2024-05-02,Interest,intereses ganados,0
70,2024-05-24,Bank Transfer,transf. cliente esposito marcelo,100000
71,2024-05-27,Services,merpago*lanaturaleza1855,11900
72,2024-05-27,Groceries,market avenida sta. fe,8836
73,2024-05-27,Groceries,dia tienda 679,8579
74,2024-05-28,Shopping,new garden,7495
75,2024-05-28,Services,merpago*juanlin,4700
76,2024-05-29,Groceries,coto sucursal 163,14979
77,2024-05-30,Services,merpago*lanaturaleza1855,5800
78,2024-05-30,Food & Dining,la finca,7760
79,2024-05-30,Groceries,dia tienda 268,4237
80,2024-05-31,Services,merpago*juanlin,7840
81,2024-06-03,Interest,intereses ganados,1
82,2024-06-06,Services,merpago*juanlin,14000
83,2024-06-06,Shopping,new garden,4400
84,2024-07-01,Interest,intereses ganados,0
85,2024-07-01,Bank Transfer,transf. cliente esposito marcelo,100000
86,2024-07-01,Bank Transfer,transferencia,30000
87,2024-07-03,Groceries,coto sucursal 163,19068
88,2024-07-04,Bank Transfer,transf. cliente tejerina maria,10000
89,2024-07-05,Shopping,new garden,9400
90,2024-07-08,Groceries,verduleria paola,11287
91,2024-07-10,Tax & Fees,imp pais sd,220
92,2024-07-10,Digital Services,apple.com bill,2900
93,2024-07-10,Groceries,coto sucursal 163,11432
94,2024-07-10,Tax & Fees,rg 4815/20,824
95,2024-07-11,Tax & Fees,iva serv digit-rg afip 4240,609
96,2024-07-12,Services,merpago*juanlin,10750
97,2024-07-12,Groceries,verduleria paola,4338
98,2024-07-12,Shopping,new garden,4400
99,2024-07-15,Bank Transfer,transf. cliente esposito marcelo,50000
100,2024-07-15,Groceries,dia tienda 268,9482
101,2024-07-15,Bank Transfer,transferencia,20000
102,2024-07-15,Bank Transfer,transferencia,10000
103,2024-07-16,Groceries,dia tienda 679,7596
104,2024-07-19,Bank Transfer,transferencia,8388
105,2024-07-22,Bank Transfer,transf. cliente esposito marcelo,50000
106,2024-07-22,Bank Transfer,transferencia,30000
107,2024-07-22,Groceries,dia tienda 679,9075
108,2024-07-25,Reimbursement,reintegro modo. 100% en tu prim,5000
109,2024-07-25,Reimbursement,reintegro modo. 20% en cualquie,1000
110,2024-07-29,Bank Transfer,transferencia,16924
111,2024-08-01,Interest,intereses ganados,1
112,2024-08-07,Bank Transfer,transf. cliente esposito marcelo,20000
113,2024-08-09,Groceries,verduleria paola,3612
114,2024-08-12,Tax & Fees,imp pais sd,225
115,2024-08-12,Digital Services,apple.com/bill,2972
116,2024-08-12,Tax & Fees,rg 4815/20,842
117,2024-08-13,Tax & Fees,iva serv digit-rg afip 4240,624
118,2024-08-26,Bank Transfer,transf. cliente esposito marcelo,50000
119,2024-08-26,Groceries,verduleria paola,8552
120,2024-08-26,Bank Transfer,transferencia,30000
121,2024-08-26,Groceries,dia tienda 679,5436
122,2024-08-27,Groceries,verduleria paola,7346
123,2024-08-28,Bank Transfer,transf. cliente esposito marcelo,30000
124,2024-08-28,Groceries,coto sucursal 163,8689

In [17]:
# Define a function to filter the dataframe based on the selected category
def filter_df(category):
    if category == 'All':
        return df
    return df[df['Category'] == category]
# Create a DataFrame widget that updates based on the category filter
summary_table = pn.widgets.DataFrame(filter_df('All'), height = 300,width=400)

# Define a callback that updates the dataframe widget when the category filter is changed
def update_summary_table(event):
    summary_table.value = filter_df(event.new)

# Add the callback function to the category widget
select_category1.param.watch(update_summary_table, 'value')

summary_table

BokehModel(combine_events=True, render_bundle={'docs_json': {'29fde988-9848-4a9e-b0a6-27659c891938': {'version…

## Create Final Dashboard

In [18]:
template = pn.template.FastListTemplate(
    title="Personal Finances Summary",
    sidebar=[
        pn.pane.Markdown("## *If you can't manage your money, making more won't help*"),
        pn.pane.PNG('finance.png', sizing_mode='scale_both'),
        pn.pane.Markdown(""),
        pn.pane.Markdown(""),
        select_category1
    ],
    main=[
        pn.Row(income_widget, recurring_expenses_widget, monthly_expenses_widget, difference_widget, width=950),
        pn.Row(last_month_expenses_chart, height=240),
        pn.GridBox(
            monthly_expenses_trend_by_cat_chart[1],
            summary_table,
            ncols=2,
            width=500,  
            align='start',
            sizing_mode='stretch_width'
        )
    ]
)

template.show()

WARNING:param.GridBox: Providing a width-responsive sizing_mode ('stretch_width') and a fixed width is not supported. Converting fixed width to min_width. If you intended the component to be fully width-responsive remove the heightsetting, otherwise change it to min_height. To error on the incorrect specification disable the config.layout_compatibility option.

Launching server at http://localhost:64601

WARNING:bokeh.core.validation.check:W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Column(id='790cc463-a584-4644-ab33-8cab57fbe257', ...)
WARNING:bokeh.core.validation.check:W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Column(id='97621b6c-2c42-4e68-bbbc-4b05dd1bb42b', ...)
WARNING:bokeh.core.validation.check:W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Column(id='b3b27a49-0bdf-4ef4-88c5-083faf167fee', ...)

2025-01-12 21:39:16,247 ERROR: panel.reactive - Callback failed for object named 'Income' changing property {'value': ''}
Traceback (most recent call last):
  File "C:\Users\esposito\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\panel\reactive.py", line 470, in _process_events
    self.param.update(**self_params)
  File "C:\Users\esposito\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\param\parameterized.py", line 2406, in update
    restore = dict(self_._update(arg, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\esposito\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\param\parameterized.py", line 2439, in _update
    self_._batch_call_watchers()
  File "C:\Users\esposito\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\param\parameterized.py", line 2624, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "C:\Users\esposito\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\param\parameterized.py", line 2586, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "C:\Users\esposito\AppData\Local\Temp\ipykernel_20252\2523706690.py", line 2, in calculate_difference
    income = float(income_widget.value)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: ''
2025-01-12 21:39:17,120 ERROR: panel.reactive - Callback failed for object named 'Recurring Expenses' changing property {'value': ''}
Traceback (most recent call last):
  File "C:\Users\esposito\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\panel\reactive.py", line 470, in _process_events
    self.param.update(**self_params)
  File "C:\Users\esposito\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\param\parameterized.py", line 2406, in update
    restore = dict(self_._update(arg, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\esposito\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\param\parameterized.py", line 2439, in _update
    self_._batch_call_watchers()
  File "C:\Users\esposito\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\param\parameterized.py", line 2624, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "C:\Users\esposito\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\param\parameterized.py", line 2586, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "C:\Users\esposito\AppData\Local\Temp\ipykernel_20252\2523706690.py", line 2, in calculate_difference
    income = float(income_widget.value)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: ''

WARNING:bokeh.core.validation.check:W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Column(id='fa59f589-aff1-4633-bdaa-6135665c9c95', ...)